#!/usr/bin/env bash
# EphemeralML GCP Init — Interactive config generator for GCP deployment.
#
# Generates a .env.gcp file with all environment variables needed for
# GCP Confidential Space deployment. Validates project access and zone
# availability.
#
# Usage:
#   bash scripts/init_gcp.sh                        # interactive (default)
#   bash scripts/init_gcp.sh --non-interactive      # CI mode (values from env vars)
#   source .env.gcp && bash scripts/gcp/deploy.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${PROJECT_DIR}/.env.gcp"

NON_INTERACTIVE=false

# Parse flags
while [[ $# -gt 0 ]]; do
    case "$1" in
        --non-interactive) NON_INTERACTIVE=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo ""
echo "EphemeralML GCP Init"
echo "===================="
echo ""

# Helper: prompt with default (or read from env in non-interactive mode)
prompt() {
    local varname="$1"
    local prompt_text="$2"
    local default="$3"
    local value

    if $NON_INTERACTIVE; then
        # In non-interactive mode, use the default (which may come from env)
        value="${default}"
    elif [ -n "${default}" ]; then
        read -r -p "${prompt_text} [${default}]: " value
        value="${value:-${default}}"
    else
        read -r -p "${prompt_text}: " value
    fi
    eval "${varname}=\"${value}\""
}

# Auto-detect GCP project
DEFAULT_PROJECT="${EPHEMERALML_GCP_PROJECT:-}"
if [ -z "${DEFAULT_PROJECT}" ] && command -v gcloud &>/dev/null; then
    DEFAULT_PROJECT="$(gcloud config get-value project 2>/dev/null || true)"
    [ "${DEFAULT_PROJECT}" = "(unset)" ] && DEFAULT_PROJECT=""
fi

prompt GCP_PROJECT "GCP Project" "${DEFAULT_PROJECT}"

if [ -z "${GCP_PROJECT}" ]; then
    echo "ERROR: GCP project is required."
    if $NON_INTERACTIVE; then
        echo "Set EPHEMERALML_GCP_PROJECT environment variable."
    fi
    exit 1
fi

# Validate project access
echo ""
echo "  Validating project access..."
if command -v gcloud &>/dev/null; then
    if gcloud projects describe "${GCP_PROJECT}" &>/dev/null; then
        echo "  Project '${GCP_PROJECT}' is accessible."
    else
        echo "  WARNING: Cannot access project '${GCP_PROJECT}'. Continuing anyway."
    fi
else
    echo "  WARNING: gcloud not installed — skipping project validation."
fi
echo ""

DEFAULT_ZONE="${EPHEMERALML_GCP_ZONE:-us-central1-a}"
DEFAULT_MODEL_SOURCE="${EPHEMERALML_MODEL_SOURCE:-local}"

prompt ZONE "Zone" "${DEFAULT_ZONE}"
prompt MODEL_SOURCE "Model source (local/gcs-kms)" "${DEFAULT_MODEL_SOURCE}"

GCS_BUCKET=""
GCP_MODEL_PREFIX=""
KMS_KEY=""
WIP_AUDIENCE=""
EXPECTED_MODEL_HASH=""

if [ "${MODEL_SOURCE}" = "gcs-kms" ]; then
    DEFAULT_BUCKET="${EPHEMERALML_GCS_BUCKET:-ephemeralml-models-${GCP_PROJECT}}"
    DEFAULT_PREFIX="${EPHEMERALML_GCP_MODEL_PREFIX:-models/minilm}"
    DEFAULT_KMS="${EPHEMERALML_GCP_KMS_KEY:-}"
    DEFAULT_WIP="${EPHEMERALML_GCP_WIP_AUDIENCE:-}"
    DEFAULT_HASH="${EPHEMERALML_EXPECTED_MODEL_HASH:-}"

    if $NON_INTERACTIVE; then
        # In non-interactive mode, require KMS key and WIP audience
        if [ -z "${DEFAULT_KMS}" ]; then
            echo "ERROR: EPHEMERALML_GCP_KMS_KEY is required in non-interactive gcs-kms mode."
            exit 1
        fi
        if [ -z "${DEFAULT_WIP}" ]; then
            echo "ERROR: EPHEMERALML_GCP_WIP_AUDIENCE is required in non-interactive gcs-kms mode."
            exit 1
        fi
    else
        echo ""
        echo "  KMS-gated model configuration:"
    fi

    prompt GCS_BUCKET "GCS bucket" "${DEFAULT_BUCKET}"
    prompt GCP_MODEL_PREFIX "GCS model prefix" "${DEFAULT_PREFIX}"
    prompt KMS_KEY "KMS key resource name" "${DEFAULT_KMS}"
    prompt WIP_AUDIENCE "WIP audience string" "${DEFAULT_WIP}"
    prompt EXPECTED_MODEL_HASH "Expected model hash (SHA-256)" "${DEFAULT_HASH}"
fi

# Write .env.gcp
echo ""
echo "  Writing ${ENV_FILE}..."

cat > "${ENV_FILE}" << EOF
# EphemeralML GCP Configuration
# Generated by: bash scripts/init_gcp.sh
# Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

export EPHEMERALML_GCP_PROJECT="${GCP_PROJECT}"
export EPHEMERALML_GCP_ZONE="${ZONE}"
export EPHEMERALML_MODEL_SOURCE="${MODEL_SOURCE}"
EOF

if [ "${MODEL_SOURCE}" = "gcs-kms" ]; then
    cat >> "${ENV_FILE}" << EOF
export EPHEMERALML_GCS_BUCKET="${GCS_BUCKET}"
export EPHEMERALML_GCP_MODEL_PREFIX="${GCP_MODEL_PREFIX}"
export EPHEMERALML_GCP_KMS_KEY="${KMS_KEY}"
export EPHEMERALML_GCP_WIP_AUDIENCE="${WIP_AUDIENCE}"
export EPHEMERALML_EXPECTED_MODEL_HASH="${EXPECTED_MODEL_HASH}"
EOF
fi

echo ""
echo "===================="
echo "  Configuration saved to: ${ENV_FILE}"
echo ""
echo "  Next steps:"
echo "    source ${ENV_FILE}"
echo "    bash scripts/gcp/deploy.sh"
echo ""
