use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Domain-separated HPKE info context for KMS recipient encryption.
///
/// Binding the recipient public key into the HPKE `info` string makes the
/// context explicit and avoids relying on a bare static label alone.
pub fn kms_hpke_info(recipient_public_key: &[u8; 32]) -> Vec<u8> {
    const LABEL: &[u8] = b"cyntrisec:kms-dek:v1";

    let mut info = Vec::with_capacity(1 + LABEL.len() + 1 + recipient_public_key.len());
    info.push(LABEL.len() as u8);
    info.extend_from_slice(LABEL);
    info.push(recipient_public_key.len() as u8);
    info.extend_from_slice(recipient_public_key);
    info
}

/// Correlation identifiers for KMS proxy requests.
///
/// `request_id` is generated by the caller (enclave) and must be echoed by the host.
/// `trace_id` is optional and can be used to stitch together multi-hop traces.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct KmsProxyRequestEnvelope {
    pub request_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
    pub request: KmsRequest,
}

/// Correlated response envelope for KMS proxy requests.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct KmsProxyResponseEnvelope {
    pub request_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
    /// AWS-side request id (when available) for debugging with AWS support / CloudTrail.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_request_id: Option<String>,
    pub response: KmsResponse,
}

/// Evidence that an attestation-bound AWS KMS release occurred.
///
/// This intentionally contains only non-secret metadata and hashes of opaque
/// ciphertexts. It is suitable for inclusion in customer evidence bundles.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct KmsReleaseEvidence {
    pub status: String,
    pub operation: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kms_key_arn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_kms_key_arn: Option<String>,
    pub aws_request_id: String,
    pub recipient_attestation: KmsRecipientAttestationEvidence,
    pub ciphertext_for_recipient_sha256: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encryption_context: Option<HashMap<String, String>>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct KmsRecipientAttestationEvidence {
    /// Filled by the runtime when the EIF PCR0/ImageSha384 is known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_sha384: Option<String>,
    /// SHA-256 of the raw Nitro attestation document sent as KMS RecipientInfo.
    pub attestation_doc_sha256: String,
}

#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum KmsProxyErrorCode {
    Timeout,
    InvalidRequest,
    UpstreamAccessDenied,
    UpstreamThrottled,
    UpstreamUnavailable,
    Internal,
}

/// KMS Request types (matching Host definition)
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(tag = "op", content = "payload")]
pub enum KmsRequest {
    Decrypt {
        ciphertext_blob: Vec<u8>,
        key_id: Option<String>,
        encryption_context: Option<HashMap<String, String>>,
        grant_tokens: Option<Vec<String>>,
        recipient: Option<Vec<u8>>, // Attestation document
    },
    GenerateDataKey {
        key_id: String,
        key_spec: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        encryption_context: Option<HashMap<String, String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        recipient: Option<Vec<u8>>,
    },
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum KmsResponse {
    Decrypt {
        /// If Recipient was provided in request, this contains the payload encrypted to the recipient key.
        ciphertext_for_recipient: Option<Vec<u8>>,
        /// If Recipient was NOT provided, this contains plaintext (NOT SAFE for Enclaves).
        plaintext: Option<Vec<u8>>,
        key_id: Option<String>,
    },
    GenerateDataKey {
        ciphertext_blob: Vec<u8>,
        #[serde(default)]
        plaintext: Option<Vec<u8>>,
        key_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        ciphertext_for_recipient: Option<Vec<u8>>,
    },
    Error {
        code: KmsProxyErrorCode,
        /// Redacted, caller-safe error message.
        message: String,
    },
}
